[build]
rustflags = [
    "-W", "clippy::all",
    "-W", "clippy::pedantic",
    "-W", "clippy::restriction",
    "-W", "clippy::nursery",
    "-A", "clippy::absolute-paths",
    "-A", "clippy::blanket-clippy-restriction-lints",
    "-A", "clippy::default-numeric-fallback",
    "-A", "clippy::derive-partial-eq-without-eq",
    "-A", "clippy::float-arithmetic",
    "-A", "clippy::future-not-send",
    "-A", "clippy::implicit-return",
    "-A", "clippy::min-ident-chars",
    "-A", "clippy::missing-docs-in-private-items",
    "-A", "clippy::missing-inline-in-public-items",
    "-A", "clippy::missing-trait-methods",
    "-A", "clippy::multiple-inherent-impl",
    "-A", "clippy::multiple-unsafe-ops-per-block",
    "-A", "clippy::print-stderr",
    "-A", "clippy::pub-with-shorthand",
    "-A", "clippy::question-mark-used",
    "-A", "clippy::mod-module-files",
    "-A", "clippy::semicolon-if-nothing-returned",
    "-A", "clippy::shadow-reuse",
    "-A", "clippy::shadow-unrelated",
    "-A", "clippy::single-call-fn",
    "-A", "clippy::single-char-lifetime-names",
    "-A", "clippy::std-instead-of-alloc",
    "-A", "clippy::std-instead-of-core",
    "-A", "clippy::tests-outside-test-module",
    "-A", "clippy::wildcard-enum-match-arm"
]
