binop_separator          = "Back"
brace_style              = "PreferSameLine"
chain_width              = 100
fn_call_width            = 80
fn_params_layout         = "Compressed"
max_width                = 120
struct_lit_width         = 80
struct_variant_width     = 80
trailing_comma           = "Never"
use_field_init_shorthand = true
where_single_line        = true
