variables:
  RUST_VERSION: 1.75.0
  GO_VERSION: '1.20'
  IMAGE: $CI_REGISTRY_IMAGE

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == 'push' && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

dummy:
  image: alpine:3.18
  script:
    - echo "dummy job"

image:rust-ci:
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug
    entrypoint: [""]
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/rust
    D_CONTEXT: rust
    D_FILE: Dockerfile
  before_script:
    - auth=$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)
    - 'echo "{\"auths\": {\"$CI_REGISTRY\": {\"auth\": \"$auth\"}}}" > /kaniko/.docker/config.json'
  script:
    - '[ "$CI_COMMIT_REF_NAME" != "$CI_DEFAULT_BRANCH" ] && dry=--no-push'
    - >-
      /kaniko/executor $dry
      --context=$D_CONTEXT
      --dockerfile=$D_FILE
      --destination $IMAGE:$RUST_VERSION
      --build-arg RUST_VERSION=$RUST_VERSION
  rules:
    - exists:
        - $D_CONTEXT/$D_FILE
      changes:
        - $D_CONTEXT/$D_FILE

image:rust-ci:alt-target:
  extends: image:rust-ci
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/rust/alt-target
    D_FILE: Dockerfile-other

image:rust-chef:
  extends: image:rust-ci
  variables:
   IMAGE: $CI_REGISTRY_IMAGE/rust/chef
   D_FILE: Dockerfile-chef

image:go-ci:
  extends: image:rust-ci
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/golang
    D_CONTEXT: golang
  script:
    - '[ "$CI_COMMIT_REF_NAME" != "$CI_DEFAULT_BRANCH" ] && dry=--no-push'
    - >-
      /kaniko/executor $dry
      --context=$D_CONTEXT
      --dockerfile=$D_FILE
      --destination $IMAGE:$GO_VERSION
      --build-arg GO_VERSION=$GO_VERSION

# ci_lint_key variable holds a personal access token to interact with Gitlab's ci/lint API.
# That API doesn't seem to respond to regular job-tokens for authorization and even if it did
# this is not one of the hard-coded APIs accessible by the job-token. Wait for:
# https://gitlab.com/groups/gitlab-org/-/epics/3559
template-check:
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:1.1.0
  script:
    - >-
      for pipeline in **/*.gitlab-ci.yml; do
      echo "Valiating: $pipeline" &&
      jq --null-input --arg yaml "$(<$pipeline)" '.content=$yaml' |
      curl -s $CI_API_V4_URL/projects/$CI_PROJECT_ID/ci/lint -X POST -d @-
      -H "PRIVATE-TOKEN: $ci_lint_key" -H 'Content-Type: application/json' |
      jq 'del(.merged_yaml)' > output.json &&
      jq '.' output.json &&
      jq -e '.valid' output.json
      ; done
  rules:
    - changes: [ '**/*.gitlab-ci.yml' ]
